import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('platform', {
  windowChrome: process.platform === 'darwin' ? 'macos-overlay' : (process.platform === 'win32' ? 'windows-overlay' : 'standard'),
  getSnapshot: () => ipcRenderer.invoke('platform:get-snapshot'),
  savePreference: (key: string, value: unknown) => ipcRenderer.invoke('platform:save-preference', key, value),
  updateMenus: (menus: unknown) => ipcRenderer.invoke('platform:update-menus', menus),
  updateMicroApps: (apps: unknown) => ipcRenderer.invoke('platform:update-microapps', apps),
  selectMicroAppDirectory: () => ipcRenderer.invoke('platform:select-microapp-directory'),
  resolveLocalMicroAppUrl: (appId: string) => ipcRenderer.invoke('platform:resolve-local-microapp-url', appId),
  getNovelApiBaseUrl: () => ipcRenderer.invoke('platform:get-novel-api-base-url'),
  testNovelModelConnection: (role: 'authoring' | 'automation', prompt?: string) => ipcRenderer.invoke('platform:test-novel-model-connection', role, prompt),
  listNovelProjects: () => ipcRenderer.invoke('platform:list-novel-projects'),
  getNovelProject: (id: string) => ipcRenderer.invoke('platform:get-novel-project', id),
  createNovelProject: (title?: string) => ipcRenderer.invoke('platform:create-novel-project', title),
  saveNovelProject: (project: unknown) => ipcRenderer.invoke('platform:save-novel-project', project),
  deleteNovelProject: (id: string) => ipcRenderer.invoke('platform:delete-novel-project', id),
  exportNovelProject: (id: string) => ipcRenderer.invoke('platform:export-novel-project', id),
  importNovelProject: (raw: string) => ipcRenderer.invoke('platform:import-novel-project', raw),
  getNovelWorkspaceSettings: () => ipcRenderer.invoke('platform:get-novel-workspace-settings'),
  saveNovelWorkspaceSettings: (settings: unknown) => ipcRenderer.invoke('platform:save-novel-workspace-settings', settings),
  exportSnapshot: () => ipcRenderer.invoke('platform:export-snapshot'),
  importSnapshot: (snapshot: string) => ipcRenderer.invoke('platform:import-snapshot', snapshot),
  restoreDefaults: () => ipcRenderer.invoke('platform:restore-defaults'),
  setTitleBarChrome: (chrome: { color: string; symbolColor: string; height?: number }) => ipcRenderer.invoke('window:set-titlebar-chrome', chrome),
  windowCommand: (action: string) => ipcRenderer.invoke('window:command', action),
  onWindowNavigate: (listener: (path: string) => void) => {
    const handler = (_event: Electron.IpcRendererEvent, path: string) => listener(path)
    ipcRenderer.on('window:navigate', handler)
    return () => ipcRenderer.removeListener('window:navigate', handler)
  },
  listModelProviders: () => ipcRenderer.invoke('harness:list-model-providers'),
  getModelConfigPath: () => ipcRenderer.invoke('harness:get-model-config-path'),
  getModelProviderApiKey: (id: string) => ipcRenderer.invoke('harness:get-model-provider-api-key', id),
  openModelConfigFile: () => ipcRenderer.invoke('harness:open-model-config-file'),
  listModelProviderModels: (provider: unknown) => ipcRenderer.invoke('harness:list-model-provider-models', provider),
  saveModelProvider: (provider: unknown) => ipcRenderer.invoke('harness:save-model-provider', provider),
  deleteModelProvider: (id: string) => ipcRenderer.invoke('harness:delete-model-provider', id),
  getModelRoleBindings: () => ipcRenderer.invoke('harness:get-model-role-bindings'),
  saveModelRoleBindings: (bindings: unknown) => ipcRenderer.invoke('harness:save-model-role-bindings', bindings),
  testModelProvider: (provider: unknown, modelId: string) => ipcRenderer.invoke('harness:test-model-provider', provider, modelId),
  listHarnessProjects: () => ipcRenderer.invoke('harness:list-projects'),
  selectHarnessProjectDirectory: () => ipcRenderer.invoke('harness:select-project-directory'),
  createHarnessProject: (input?: unknown) => ipcRenderer.invoke('harness:create-project', input),
  renameHarnessProject: (id: string, name: string) => ipcRenderer.invoke('harness:rename-project', id, name),
  deleteHarnessProject: (id: string, removeMira?: boolean) => ipcRenderer.invoke('harness:delete-project', id, removeMira),
  listHarnessSessions: (query?: string) => ipcRenderer.invoke('harness:list-sessions', query),
  createHarnessSession: (projectId?: string) => ipcRenderer.invoke('harness:create-session', projectId),
  getHarnessSession: (id: string) => ipcRenderer.invoke('harness:get-session', id),
  deleteHarnessSession: (id: string) => ipcRenderer.invoke('harness:delete-session', id),
  deleteHarnessSessions: (ids: string[]) => ipcRenderer.invoke('harness:delete-sessions', ids),
  listHarnessProjectFiles: (projectId: string, query?: string) => ipcRenderer.invoke('harness:list-project-files', projectId, query),
  attachHarnessDirectory: (sessionId: string) => ipcRenderer.invoke('harness:attach-directory', sessionId),
  runHarnessMessage: (sessionId: string, message: string, references?: unknown[], selection?: unknown) => ipcRenderer.invoke('harness:run-message', sessionId, message, references, selection),
  abortHarnessRun: (sessionId: string) => ipcRenderer.invoke('harness:abort-run', sessionId),
  getHarnessPermissionConfig: () => ipcRenderer.invoke('harness:get-permission-config'),
  saveHarnessPermissionConfig: (config: unknown) => ipcRenderer.invoke('harness:save-permission-config', config),
  onHarnessEvent: (listener: (event: unknown) => void) => {
    const handler = (_event: Electron.IpcRendererEvent, event: unknown) => listener(event)
    ipcRenderer.on('harness:event', handler)
    return () => ipcRenderer.removeListener('harness:event', handler)
  },
  getPythonStatus: () => ipcRenderer.invoke('harness:python-status'),
  pythonExec: (script: string, args: string[] = []) => ipcRenderer.invoke('harness:python-exec', script, args),
  pythonInstallPackage: (packageName: string) => ipcRenderer.invoke('harness:python-install-package', packageName),
})
