import { ipcRenderer } from 'electron'

export const harnessApi = {
  listHarnessSkills: () => ipcRenderer.invoke('harness:list-skills'),
  getHarnessSkillSettings: () => ipcRenderer.invoke('harness:get-skill-settings'),
  saveHarnessSkillSettings: (settings: unknown) => ipcRenderer.invoke('harness:save-skill-settings', settings),
  setHarnessSkillEnabled: (id: string, enabled: boolean) => ipcRenderer.invoke('harness:set-skill-enabled', id, enabled),
  listHarnessProjects: () => ipcRenderer.invoke('harness:list-projects'),
  reorderHarnessProjects: (ids: string[]) => ipcRenderer.invoke('harness:reorder-projects', ids),
  openHarnessProjectDirectory: (id: string) => ipcRenderer.invoke('harness:open-project-directory', id),
  selectHarnessProjectDirectory: () => ipcRenderer.invoke('harness:select-project-directory'),
  createHarnessProject: (input?: unknown) => ipcRenderer.invoke('harness:create-project', input),
  renameHarnessProject: (id: string, name: string, icon?: string) => ipcRenderer.invoke('harness:rename-project', id, name, icon),
  deleteHarnessProject: (id: string) => ipcRenderer.invoke('harness:delete-project', id),
  getGlobalInstructions: () => ipcRenderer.invoke('harness:get-global-instructions'),
  saveGlobalInstructions: (content: string) => ipcRenderer.invoke('harness:save-global-instructions', content),
  getGlobalInstructionsPath: () => ipcRenderer.invoke('harness:get-global-instructions-path'),
  getHarnessMemoryEnabled: () => ipcRenderer.invoke('harness:get-memory-enabled'),
  setHarnessMemoryEnabled: (enabled: boolean) => ipcRenderer.invoke('harness:set-memory-enabled', enabled),
  getHarnessMemoryPath: () => ipcRenderer.invoke('harness:get-memory-path'),
  resetHarnessMemory: () => ipcRenderer.invoke('harness:reset-memory'),
  listHarnessMemory: (scope: unknown, projectId?: string) => ipcRenderer.invoke('harness:list-memory', scope, projectId),
  rememberHarnessMemory: (content: string) => ipcRenderer.invoke('harness:remember-memory', content),
  updateHarnessMemory: (scope: unknown, id: string, content: string, projectId?: string) => ipcRenderer.invoke('harness:update-memory', scope, id, content, projectId),
  deleteHarnessMemory: (scope: unknown, id: string, projectId?: string) => ipcRenderer.invoke('harness:delete-memory', scope, id, projectId),
  listPendingHarnessMemory: () => ipcRenderer.invoke('harness:list-pending-memory'),
  discardHarnessMemory: (candidateId: string) => ipcRenderer.invoke('harness:discard-pending-memory', candidateId),
  retryHarnessMemory: (candidateId: string) => ipcRenderer.invoke('harness:retry-memory', candidateId),
  respondHarnessMemoryConfirmation: (requestId: string, approved: boolean) => ipcRenderer.invoke('harness:respond-memory-confirmation', requestId, approved),
  listHarnessGitBranches: (projectId: string) => ipcRenderer.invoke('harness:list-git-branches', projectId),
  checkoutHarnessGitBranch: (projectId: string, branchName: string) => ipcRenderer.invoke('harness:checkout-git-branch', projectId, branchName),
  createAndCheckoutHarnessGitBranch: (projectId: string, branchName: string) => ipcRenderer.invoke('harness:create-and-checkout-git-branch', projectId, branchName),
  listHarnessSessions: (query?: string) => ipcRenderer.invoke('harness:list-sessions', query),
  reorderHarnessSessions: (scope: unknown, ids: string[]) => ipcRenderer.invoke('harness:reorder-sessions', scope, ids),
  queryHarnessHistory: (query: unknown) => ipcRenderer.invoke('harness:query-history', query),
  queryHarnessUsage: () => ipcRenderer.invoke('harness:query-usage'),
  createHarnessSession: (projectId?: string) => ipcRenderer.invoke('harness:create-session', projectId),
  getHarnessSession: (id: string) => ipcRenderer.invoke('harness:get-session', id),
  setHarnessSessionPermission: (id: string, permissionMode: unknown) => ipcRenderer.invoke('harness:set-permission', id, permissionMode),
  setHarnessActiveSkills: (id: string, skillIds: string[]) => ipcRenderer.invoke('harness:set-active-skills', id, skillIds),
  setHarnessActiveMcpServers: (id: string, serverIds: string[]) => ipcRenderer.invoke('harness:set-active-mcp-servers', id, serverIds),
  setHarnessDelegationEnabled: (id: string, enabled: boolean) => ipcRenderer.invoke('harness:set-delegation-enabled', id, enabled),
  saveHarnessProjectMemory: (id: string, selection: unknown) => ipcRenderer.invoke('harness:save-project-memory', id, selection),
  setHarnessSessionPinned: (id: string, pinned: boolean) => ipcRenderer.invoke('harness:set-pinned', id, pinned),
  setHarnessSessionUnread: (id: string, unread: boolean) => ipcRenderer.invoke('harness:set-unread', id, unread),
  moveHarnessSession: (id: string, projectId: string) => ipcRenderer.invoke('harness:move-session', id, projectId),
  renameHarnessSession: (id: string, title: string) => ipcRenderer.invoke('harness:rename-session', id, title),
  archiveHarnessSessions: (ids: string[]) => ipcRenderer.invoke('harness:archive-sessions', ids),
  restoreHarnessSessions: (ids: string[]) => ipcRenderer.invoke('harness:restore-sessions', ids),
  deleteHarnessSession: (id: string) => ipcRenderer.invoke('harness:delete-session', id),
  deleteHarnessSessions: (ids: string[]) => ipcRenderer.invoke('harness:delete-sessions', ids),
  openHarnessSessionProject: (id: string, target: 'file-manager' | 'terminal') => ipcRenderer.invoke('harness:open-session-project', id, target),
  listHarnessProjectFiles: (projectId: string, query?: string) => ipcRenderer.invoke('harness:list-project-files', projectId, query),
  selectHarnessFiles: (projectId: string) => ipcRenderer.invoke('harness:select-files', projectId),
  attachHarnessDirectory: (sessionId: string) => ipcRenderer.invoke('harness:attach-directory', sessionId),
  runHarnessMessage: (sessionId: string, message: string, references?: unknown[], selection?: unknown, planning?: boolean) => ipcRenderer.invoke('harness:run-message', sessionId, message, references, selection, planning),
  confirmHarnessPlan: (sessionId: string, planId: string, selection?: unknown) => ipcRenderer.invoke('harness:confirm-plan', sessionId, planId, selection),
  answerHarnessInteraction: (sessionId: string, interactionId: string, answers: unknown, selection?: unknown) => ipcRenderer.invoke('harness:answer-interaction', sessionId, interactionId, answers, selection),
  continueHarnessPlan: (sessionId: string, planId: string, message: string, references?: unknown[], selection?: unknown) => ipcRenderer.invoke('harness:continue-plan', sessionId, planId, message, references, selection),
  cancelHarnessPlan: (sessionId: string, planId: string) => ipcRenderer.invoke('harness:cancel-plan', sessionId, planId),
  rerunHarness: (sessionId: string, selection?: unknown) => ipcRenderer.invoke('harness:rerun', sessionId, selection),
  editAndRerunHarnessMessage: (sessionId: string, messageId: string, content: string, selection?: unknown) => ipcRenderer.invoke('harness:edit-and-rerun', sessionId, messageId, content, selection),
  abortHarnessRun: (sessionId: string) => ipcRenderer.invoke('harness:abort-run', sessionId),
  stopHarnessSubtasks: (sessionId: string, ids?: string[]) => ipcRenderer.invoke('harness:stop-subtasks', sessionId, ids),
  getHarnessPermissionConfig: () => ipcRenderer.invoke('harness:get-permission-config'),
  saveHarnessPermissionConfig: (config: unknown) => ipcRenderer.invoke('harness:save-permission-config', config),
  getHarnessGitConfig: () => ipcRenderer.invoke('harness:get-git-config'),
  saveHarnessGitConfig: (config: unknown) => ipcRenderer.invoke('harness:save-git-config', config),
  listHarnessTrash: (projectId?: string) => ipcRenderer.invoke('harness:list-trash', projectId),
  restoreHarnessTrash: (projectId: string, token: string) => ipcRenderer.invoke('harness:restore-trash', projectId, token),
  onHarnessEvent: (listener: (event: unknown) => void) => {
    const handler = (_event: Electron.IpcRendererEvent, event: unknown) => listener(event)
    ipcRenderer.on('harness:event', handler)
    return () => ipcRenderer.removeListener('harness:event', handler)
  },
  respondHarnessPermission: (requestId: string, allowed: boolean) => ipcRenderer.invoke('harness:respond-permission', requestId, allowed),
  getPythonStatus: () => ipcRenderer.invoke('harness:python-status'),
  pythonExec: (script: string, args: string[] = []) => ipcRenderer.invoke('harness:python-exec', script, args),
  pythonInstallPackage: (packageName: string) => ipcRenderer.invoke('harness:python-install-package', packageName),
}
