<template>
  <el-drawer v-model="visible" :title="`${task?.name || ''} · 运行记录`" direction="rtl" size="min(620px, 56vw)" @open="load">
    <template #header><div class="runs-header"><div><strong>{{ task?.name || '运行记录' }}</strong><span>{{ task ? triggerLabel(task) : '' }}</span></div></div></template>
    <div class="runs-toolbar"><el-radio-group v-model="filter" size="small"><el-radio-button value="all">全部</el-radio-button><el-radio-button value="running">运行中</el-radio-button><el-radio-button value="completed">成功</el-radio-button><el-radio-button value="failed">失败</el-radio-button><el-radio-button value="skipped">跳过</el-radio-button></el-radio-group></div>
    <div v-if="loading" v-loading="loading" class="runs-loading" />
    <el-empty v-else-if="!filteredRuns.length" description="暂无符合条件的运行记录" />
    <section v-else class="run-list"><article v-for="run in filteredRuns" :key="run.id" class="run-row" :class="`is-${run.status}`"><header><span class="run-status" :class="`is-${run.status}`">{{ runStatusLabel(run.status) }}</span><time>{{ formatAutomationTime(run.startedAt || run.completedAt || run.scheduledAt) }}</time></header><p :class="{ error: run.status === 'failed' }">{{ run.error || run.resultSummary || '任务正在运行。' }}</p><details v-if="run.status === 'failed' && run.error"><summary>查看错误详情</summary><pre>{{ run.error }}</pre></details><footer><span>来源：{{ sourceLabel(run.source) }} · 权限：{{ permissionLabel(run.snapshot.permissionMode) }}</span><div><el-button v-if="run.status === 'failed'" link type="primary" :loading="retryingId === run.id" @click="retry(run)">重试</el-button><el-button v-if="run.status === 'running'" link type="danger" @click="$emit('stop')">停止</el-button><el-button v-if="run.sessionId && run.sessionAvailable !== false" link type="primary" @click="$emit('open-session', run.sessionId)">打开聊天</el-button><span v-else-if="run.sessionId" class="run-session-missing"><AppIcon name="Warning" />聊天已删除</span></div></footer></article></section>
  </el-drawer>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import type { AutomationRun, AutomationRunStatus, AutomationTask } from '@/config/harness'
import { getPlatformApi } from '@/platform'
import { formatAutomationTime, permissionLabel, runStatusLabel, sourceLabel, triggerLabel } from '../automationPresentation'

const props = defineProps<{ modelValue: boolean, task?: AutomationTask }>()
const emit = defineEmits<{ 'update:modelValue': [value: boolean], stop: [], 'open-session': [sessionId: string], changed: [] }>()
const visible = ref(props.modelValue); const loading = ref(false); const runs = ref<AutomationRun[]>([]); const filter = ref<'all' | AutomationRunStatus>('all'); const retryingId = ref('')
const filteredRuns = computed(() => filter.value === 'all' ? runs.value : runs.value.filter(run => run.status === filter.value))
watch(() => props.modelValue, value => visible.value = value); watch(visible, value => emit('update:modelValue', value)); watch(() => props.task?.id, () => { if (visible.value) void load() })
async function load() { if (!props.task) return; loading.value = true; try { runs.value = await getPlatformApi()?.listAutomationRuns(props.task.id) || [] } catch (cause) { ElMessage.error(cause instanceof Error ? cause.message : '读取运行记录失败') } finally { loading.value = false } }
async function retry(run: AutomationRun) { const api = getPlatformApi(); if (!api) return; retryingId.value = run.id; try { await api.retryAutomationRun(run.id); ElMessage.success('已创建重试任务'); await load(); emit('changed') } catch (cause) { ElMessage.error(cause instanceof Error ? cause.message : '重试失败') } finally { retryingId.value = '' } }
</script>

<style scoped lang="scss">
.runs-header { display: grid; gap: 3px; }.runs-header strong { color: var(--cp-text); font-size: 16px; }.runs-header span { color: var(--cp-text-secondary); font-size: 12px; }.runs-toolbar { margin-bottom: 16px; overflow-x: auto; }.runs-loading { min-height: 180px; }.run-list { display: grid; gap: 10px; }.run-row { padding: 13px 14px; border: 1px solid var(--cp-border-light); border-radius: $radius-sm; background: var(--cp-bg); }.run-row.is-failed { border-color: color-mix(in srgb, var(--cp-danger) 34%, var(--cp-border)); }.run-row header, .run-row footer { display: flex; align-items: center; justify-content: space-between; gap: 10px; }.run-status { display: inline-flex; padding: 3px 7px; border-radius: 999px; color: var(--cp-text-secondary); background: var(--cp-bg-hover); font-size: 11px; font-weight: 600; }.run-status.is-completed { color: var(--cp-success); background: color-mix(in srgb, var(--cp-success) 10%, var(--cp-bg)); }.run-status.is-failed { color: var(--cp-danger); background: color-mix(in srgb, var(--cp-danger) 10%, var(--cp-bg)); }.run-status.is-running { color: var(--cp-primary); background: var(--cp-primary-lighter); }.run-status.is-skipped, .run-status.is-interrupted { color: var(--cp-warning); background: color-mix(in srgb, var(--cp-warning) 10%, var(--cp-bg)); }.run-row time, .run-row footer span { color: var(--cp-text-tertiary); font-size: 12px; }.run-row p { margin: 10px 0; color: var(--cp-text-secondary); font-size: 13px; line-height: 1.55; white-space: pre-wrap; }.run-row p.error { color: var(--cp-danger); }.run-row details { margin: 8px 0; color: var(--cp-text-secondary); font-size: 12px; }.run-row summary { cursor: pointer; }.run-row pre { margin: 7px 0 0; padding: 8px; overflow: auto; border-radius: $radius-sm; color: var(--cp-text-secondary); background: var(--cp-bg-hover); font: 11px/1.5 ui-monospace, SFMono-Regular, Consolas, monospace; white-space: pre-wrap; }.run-row footer { padding-top: 10px; border-top: 1px solid var(--cp-border-light); }.run-row footer > div { display: flex; align-items: center; gap: 6px; }.run-row footer .run-session-missing { display: inline-flex; align-items: center; gap: 4px; color: var(--cp-text-tertiary); white-space: nowrap; }
</style>
