import type { MenuItem } from '@/types'

export const MENU_LIST: MenuItem[] = [
  {
    id: 'dashboard',
    title: '工作台',
    icon: 'Odometer',
    path: '/dashboard',
    name: 'Dashboard',
    component: '/pages/dashboard/DashboardPage.vue',
    permission: 'dashboard:view',
  },
  {
    id: 'system',
    title: '系统管理',
    icon: 'Setting',
    permission: 'system:view',
    children: [
      {
        id: 'system-users',
        title: '用户管理',
        icon: 'User',
        path: '/system/users',
        name: 'SystemUsers',
        component: '/pages/system/UserPage.vue',
        permission: 'system:user:view',
      },
      {
        id: 'system-roles',
        title: '角色管理',
        icon: 'UserFilled',
        path: '/system/roles',
        name: 'SystemRoles',
        component: '/pages/system/RolePage.vue',
        permission: 'system:role:view',
      },
      {
        id: 'system-menus',
        title: '菜单管理',
        icon: 'Menu',
        path: '/system/menus',
        name: 'SystemMenus',
        component: '/pages/system/MenuPage.vue',
        permission: 'system:menu:view',
      },
      {
        id: 'system-dept',
        title: '部门管理',
        icon: 'OfficeBuilding',
        path: '/system/dept',
        name: 'SystemDept',
        component: '/pages/system/DeptPage.vue',
        permission: 'system:dept:view',
      },
      {
        id: 'system-log',
        title: '操作日志',
        icon: 'Document',
        path: '/system/log',
        name: 'SystemLog',
        component: '/pages/system/LogPage.vue',
        permission: 'system:log:view',
      },
      {
        id: 'system-settings',
        title: '系统设置',
        icon: 'Tools',
        path: '/system/settings',
        name: 'SystemSettings',
        component: '/pages/system/SettingsPage.vue',
        permission: 'system:settings:view',
      },
    ],
  },
  {
    id: 'profile',
    title: '个人中心',
    icon: 'UserFilled',
    permission: 'profile:view',
    children: [
      {
        id: 'profile-info',
        title: '个人资料',
        icon: 'User',
        path: '/profile/info',
        name: 'ProfileInfo',
        component: '/pages/profile/ProfileInfoPage.vue',
        permission: 'profile:info:view',
      },
      {
        id: 'profile-security',
        title: '安全设置',
        icon: 'Lock',
        path: '/profile/security',
        name: 'ProfileSecurity',
        component: '/pages/profile/ProfileSecurityPage.vue',
        permission: 'profile:security:view',
      },
    ],
  },
  {
    id: 'message',
    title: '消息中心',
    icon: 'ChatDotRound',
    permission: 'message:view',
    children: [
      {
        id: 'message-list',
        title: '站内消息',
        icon: 'Message',
        path: '/message/list',
        name: 'MessageList',
        component: '/pages/message/MessageListPage.vue',
        permission: 'message:list:view',
      },
      {
        id: 'message-settings',
        title: '通知设置',
        icon: 'Bell',
        path: '/message/settings',
        name: 'MessageSettings',
        component: '/pages/message/MessageSettingsPage.vue',
        permission: 'message:settings:view',
      },
    ],
  },
  {
    id: 'components',
    title: '组件演示',
    icon: 'Grid',
    permission: 'components:view',
    children: [
      {
        id: 'components-table',
        title: 'ProTable',
        icon: 'Document',
        path: '/components/table',
        name: 'ComponentsTable',
        component: '/pages/components/ProTableDemo.vue',
        permission: 'components:table:view',
      },
      {
        id: 'components-form',
        title: 'ProForm',
        icon: 'Edit',
        path: '/components/form',
        name: 'ComponentsForm',
        component: '/pages/components/ProFormDemo.vue',
        permission: 'components:form:view',
      },
      {
        id: 'components-detail',
        title: 'DetailLayout',
        icon: 'Reading',
        path: '/components/detail',
        name: 'ComponentsDetail',
        component: '/pages/components/DetailLayoutDemo.vue',
        permission: 'components:detail:view',
      },
    ],
  },
]
