<template>
  <main class="harness-page">
    <section class="conversation">
      <header class="conversation__header"><div><strong>{{ store.activeSession?.title || '新对话' }}</strong><span>{{ store.activeSession?.workingDirectory || '选择项目后可使用文件工具' }}</span></div><div class="conversation__actions"><el-tag effect="plain">{{ permissionLabel }}</el-tag><el-button text :loading="attaching" @click="attachDirectory"><AppIcon name="FolderOpened" />工作目录</el-button></div></header>
      <div ref="streamRef" class="message-stream"><el-empty v-if="!store.activeSession?.messages.length" description="描述你想完成的工作即可开始" :image-size="88" /><article v-for="message in store.activeSession?.messages" :key="message.id" class="message" :class="message.role"><span class="message__role">{{ message.role === 'user' ? '你' : 'Mira' }}</span><p>{{ message.content }}</p></article></div>
      <footer class="composer"><el-input v-model="draft" type="textarea" :autosize="{ minRows: 2, maxRows: 6 }" resize="none" placeholder="输入任务，⌘ Enter 发送" :disabled="store.running" @keydown.meta.enter.prevent="send" @keydown.ctrl.enter.prevent="send" /><div><span>⌘ Enter 发送</span><el-button v-if="store.running" type="danger" plain @click="abort">停止</el-button><el-button v-else type="primary" :disabled="!draft.trim()" @click="send"><AppIcon name="Promotion" />发送</el-button></div></footer>
    </section>
    <aside class="session-panel"><section><h2>会话信息</h2><dl><div><dt>模型</dt><dd>{{ store.activeSession?.modelId || '使用默认模型' }}</dd></div><div><dt>权限</dt><dd>{{ permissionLabel }}</dd></div><div><dt>工作目录</dt><dd>{{ store.activeSession?.workingDirectory || '尚未选择' }}</dd></div></dl></section><section><h2>工具调用</h2><el-empty v-if="!store.activeSession?.toolCalls.length" description="调用工具后显示记录" :image-size="56" /><div v-for="tool in store.activeSession?.toolCalls" :key="tool.id" class="tool-row"><span :class="tool.status" />{{ tool.tool }}<small>{{ tool.target }}</small></div></section></aside>
  </main>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { getPlatformApi } from '@/platform'
import { useHarnessStore } from '@/stores/harness'

const route = useRoute(); const router = useRouter(); const store = useHarnessStore()
const draft = ref(''); const attaching = ref(false); const streamRef = ref<HTMLElement>(); let dispose: (() => void) | undefined
const permissionLabel = computed(() => ({ default: '默认权限', 'auto-approve': '自动审核', full: '完全访问' }[store.activeSession?.permissionMode || 'auto-approve']))
async function load() { await store.refreshSessions(); const id = typeof route.params.id === 'string' ? route.params.id : undefined; const session = id ? await store.openSession(id) : await store.createSession(); if (session && !id) await router.replace(`/workspace/chat/${session.id}`) }
async function send() { const api = getPlatformApi(); const text = draft.value.trim(); if (!api || !store.activeSession || !text) return; draft.value = ''; store.activeSession.messages.push({ id: `local-${Date.now()}`, role: 'user', content: text, createdAt: Date.now() }); store.running = true; try { await api.runHarnessMessage(store.activeSession.id, text) } catch (error) { ElMessage.error(error instanceof Error ? error.message : '消息发送失败'); await store.openSession(store.activeSession.id) } finally { store.running = false } }
async function abort() { if (store.activeSession) await getPlatformApi()?.abortHarnessRun(store.activeSession.id) }
async function attachDirectory() { if (!store.activeSession) return; attaching.value = true; try { const session = await getPlatformApi()?.attachHarnessDirectory(store.activeSession.id); if (session) store.activeSession = session } finally { attaching.value = false } }
watch(() => store.activeSession?.messages.length, async () => { await nextTick(); streamRef.value?.scrollTo({ top: streamRef.value.scrollHeight }) })
watch(() => route.params.id, () => { if (route.params.id) void store.openSession(String(route.params.id)) })
onMounted(() => { dispose = getPlatformApi()?.onHarnessEvent(store.applyEvent); void load() }); onBeforeUnmount(() => dispose?.())
</script>

<style scoped lang="scss">
.harness-page { height: 100%; min-height: 0; display: grid; grid-template-columns: minmax(0, 1fr) 236px; background: var(--cp-bg); border-top: 1px solid var(--cp-border-light); }.session-panel { min-width: 0; padding: $spacing-lg; overflow-y: auto; background: var(--cp-bg-elevated); border-left: 1px solid var(--cp-border-light); }.conversation { display: grid; min-width: 0; grid-template-rows: auto minmax(0, 1fr) auto; }.conversation__header { display: flex; justify-content: space-between; align-items: center; gap: $spacing-md; padding: 13px 20px; border-bottom: 1px solid var(--cp-border-light); }.conversation__header strong, .conversation__header span { display: block; }.conversation__header span { max-width: 44vw; margin-top: 3px; overflow: hidden; color: var(--cp-text-tertiary); font-size: 11px; text-overflow: ellipsis; white-space: nowrap; }.conversation__actions { display: flex; align-items: center; }.message-stream { padding: 28px clamp(20px, 4vw, 64px); overflow-y: auto; }.message { max-width: 78%; margin: 0 0 20px; }.message.user { margin-left: auto; }.message__role { display: block; margin-bottom: 6px; color: var(--cp-text-tertiary); font-size: 12px; }.message.user .message__role { text-align: right; }.message p { margin: 0; padding: 11px 13px; border-radius: $radius-md; white-space: pre-wrap; line-height: 1.7; background: var(--cp-bg-hover); }.message.user p { color: white; background: var(--cp-primary); }.composer { padding: 14px 20px; background: var(--cp-bg-elevated); border-top: 1px solid var(--cp-border-light); }.composer > div { display: flex; align-items: center; justify-content: space-between; margin-top: 8px; }.composer span { color: var(--cp-text-tertiary); font-size: 11px; }.session-panel h2 { margin: 0 0 12px; font-size: $font-sm; }.session-panel section + section { margin-top: 28px; }.session-panel dl { margin: 0; }.session-panel dl div { margin-bottom: 12px; }.session-panel dt { color: var(--cp-text-tertiary); font-size: 11px; }.session-panel dd { margin: 3px 0 0; overflow-wrap: anywhere; font-size: 12px; line-height: 1.5; }.tool-row { display: grid; grid-template-columns: 8px minmax(0, 1fr); gap: 5px; align-items: start; margin: 9px 0; font-size: 12px; }.tool-row > span { width: 7px; height: 7px; margin-top: 5px; border-radius: 50%; background: var(--cp-text-tertiary); }.tool-row > span.running { background: var(--cp-primary); }.tool-row > span.ok { background: var(--cp-success); }.tool-row > span.failed { background: var(--cp-danger); }.tool-row small { grid-column: 2; overflow: hidden; color: var(--cp-text-tertiary); text-overflow: ellipsis; white-space: nowrap; }@include media-max($breakpoint-lg) { .harness-page { grid-template-columns: 1fr; }.session-panel { display: none; } }@include media-max($breakpoint-md) { .conversation__header { padding: 10px 14px; }.message-stream { padding: 20px; }.composer { padding: 10px; } }
</style>
