<template>
  <SettingsPageShell title="记忆" wide>
    <div class="memory-page">
      <section class="memory-controls"><div><h2>长期记忆</h2><p>完成的对话会提炼为可编辑的参考资料，仅在相关项目或问题中提供给 Mira。</p></div><div class="memory-controls__actions"><el-switch v-model="autoEnabled" active-text="自动记忆" @change="saveAutoEnabled" /><el-button type="primary" @click="openCreate"><AppIcon name="Plus" />添加记忆</el-button></div></section>
      <section class="memory-filters" aria-label="记忆筛选"><el-segmented v-model="scope" :options="scopeOptions" /><el-select v-if="scope === 'project'" v-model="projectId" clearable placeholder="选择项目"><el-option v-for="project in projects" :key="project.id" :label="project.name" :value="project.id" /></el-select><el-button v-if="scope === 'project' && projectId" text type="danger" @click="clearProject">清空该项目记忆</el-button></section>
      <section v-loading="loading" class="memory-list"><el-empty v-if="!loading && filtered.length === 0" description="还没有符合条件的记忆" /><article v-for="memory in filtered" :key="memory.id" class="memory-item" :class="{ 'is-disabled': !memory.enabled }"><div class="memory-item__body"><div class="memory-item__meta"><el-tag size="small" effect="plain">{{ kindLabel(memory.kind) }}</el-tag><span>{{ memory.scope === 'global' ? '全局' : projectName(memory.projectId) }}</span><span>{{ formatTime(memory.updatedAt) }}</span></div><p>{{ memory.content }}</p></div><div class="memory-item__actions"><el-tooltip :content="memory.enabled ? '停用记忆' : '启用记忆'"><el-button text circle :aria-label="memory.enabled ? '停用记忆' : '启用记忆'" @click="toggle(memory)"><AppIcon :name="memory.enabled ? 'View' : 'Hide'" /></el-button></el-tooltip><el-tooltip content="编辑记忆"><el-button text circle aria-label="编辑记忆" @click="edit(memory)"><AppIcon name="EditPen" /></el-button></el-tooltip><el-tooltip content="删除记忆"><el-button text circle type="danger" aria-label="删除记忆" @click="remove(memory)"><AppIcon name="Delete" /></el-button></el-tooltip></div></article></section>
    </div>
    <el-dialog v-model="editorVisible" :title="form.id ? '编辑记忆' : '添加记忆'" width="min(620px, calc(100vw - 32px))" align-center><el-form label-position="top"><el-form-item label="范围"><el-segmented v-model="form.scope" :options="scopeOptions.filter(item => item.value !== 'all')" /></el-form-item><el-form-item v-if="form.scope === 'project'" label="项目"><el-select v-model="form.projectId" placeholder="选择项目"><el-option v-for="project in projects" :key="project.id" :label="project.name" :value="project.id" /></el-select></el-form-item><el-form-item label="类型"><el-select v-model="form.kind"><el-option v-for="item in kinds" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item><el-form-item label="内容"><el-input v-model="form.content" type="textarea" :rows="7" maxlength="1800" show-word-limit placeholder="记录长期有效的偏好、约束、项目事实或经验" /></el-form-item><el-form-item label="状态"><el-switch v-model="form.enabled" active-text="启用" inactive-text="停用" /></el-form-item></el-form><template #footer><el-button @click="editorVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
  </SettingsPageShell>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getPlatformApi } from '@/platform'
import type { MemoryKind, MiraMemory, MemoryScope, HarnessProject } from '@/config/harness'
import SettingsPageShell from '../settings/components/SettingsPageShell.vue'

const scope = ref<MemoryScope | 'all'>('all'), projectId = ref<string>(), memories = ref<MiraMemory[]>([]), projects = ref<HarnessProject[]>([]), loading = ref(false), saving = ref(false), autoEnabled = ref(true), editorVisible = ref(false)
const scopeOptions = [{ label: '全部', value: 'all' }, { label: '全局', value: 'global' }, { label: '项目', value: 'project' }]
const kinds: Array<{ label: string, value: MemoryKind }> = [{ label: '任务摘要', value: 'task-summary' }, { label: '项目事实', value: 'project-fact' }, { label: '用户偏好', value: 'user-preference' }, { label: '可复用经验', value: 'reusable-knowledge' }]
const form = reactive<Partial<MiraMemory> & { scope: MemoryScope, kind: MemoryKind, content: string, enabled: boolean }>({ scope: 'global', kind: 'project-fact', content: '', enabled: true })
const filtered = computed(() => memories.value.filter(memory => (scope.value === 'all' || memory.scope === scope.value) && (!projectId.value || memory.projectId === projectId.value)))
function kindLabel(kind: MemoryKind) { return kinds.find(item => item.value === kind)?.label || '任务摘要' }
function projectName(id?: string) { return projects.value.find(project => project.id === id)?.name || '已移除项目' }
function formatTime(value: number) { return new Intl.DateTimeFormat('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(value) }
async function load() { const api = getPlatformApi(); loading.value = true; try { const [items, list, enabled] = await Promise.all([api?.listHarnessMemories() || [], api?.listHarnessProjects() || [], api?.getHarnessMemoryAutoEnabled() ?? true]); memories.value = items; projects.value = list; autoEnabled.value = enabled } finally { loading.value = false } }
async function saveAutoEnabled(value: boolean) { await getPlatformApi()?.setHarnessMemoryAutoEnabled(value); ElMessage.success(value ? '已启用自动记忆' : '已停用自动记忆') }
function openCreate() { Object.assign(form, { id: undefined, scope: scope.value === 'project' ? 'project' : 'global', projectId: projectId.value, kind: 'project-fact', content: '', enabled: true }); editorVisible.value = true }
function edit(memory: MiraMemory) { Object.assign(form, memory); editorVisible.value = true }
async function save() { const api = getPlatformApi(); if (!api) return; if (!form.content.trim()) return ElMessage.error('请填写记忆内容'); if (form.scope === 'project' && !form.projectId) return ElMessage.error('请选择项目'); saving.value = true; try { await api.saveHarnessMemory({ ...form }); editorVisible.value = false; await load(); ElMessage.success('记忆已保存') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '保存失败') } finally { saving.value = false } }
async function toggle(memory: MiraMemory) { await getPlatformApi()?.saveHarnessMemory({ ...memory, enabled: !memory.enabled }); await load() }
async function remove(memory: MiraMemory) { await ElMessageBox.confirm('删除后不会再作为对话参考。', '删除记忆', { type: 'warning' }); await getPlatformApi()?.deleteHarnessMemory(memory.id); await load(); ElMessage.success('记忆已删除') }
async function clearProject() { if (!projectId.value) return; await ElMessageBox.confirm('将删除该项目的全部长期记忆，无法恢复。', '清空项目记忆', { type: 'warning' }); await getPlatformApi()?.clearHarnessProjectMemories(projectId.value); await load(); ElMessage.success('项目记忆已清空') }
onMounted(load)
</script>

<style scoped lang="scss">
.memory-page { display: flex; flex-direction: column; gap: 20px; max-width: 960px; }.memory-controls { display: flex; justify-content: space-between; align-items: center; gap: 24px; padding-bottom: 20px; border-bottom: 1px solid var(--cp-border-light); }.memory-controls h2,.memory-controls p,.memory-item p { margin: 0; }.memory-controls h2 { font-size: 18px; color: var(--cp-text); }.memory-controls p { margin-top: 6px; max-width: 620px; color: var(--cp-text-secondary); font-size: 13px; line-height: 1.6; }.memory-controls__actions,.memory-filters,.memory-item__meta,.memory-item__actions { display: flex; align-items: center; gap: 10px; }.memory-filters { min-height: 32px; }.memory-filters .el-select { width: 190px; }.memory-list { display: flex; flex-direction: column; min-height: 180px; border-top: 1px solid var(--cp-border-light); }.memory-item { display: flex; align-items: flex-start; gap: 18px; padding: 16px 4px 16px 0; border-bottom: 1px solid var(--cp-border-light); }.memory-item.is-disabled { opacity: .56; }.memory-item__body { min-width: 0; flex: 1; }.memory-item__meta { color: var(--cp-text-tertiary); font-size: 12px; }.memory-item p { margin-top: 8px; color: var(--cp-text); white-space: pre-wrap; line-height: 1.65; }.memory-item__actions { flex: 0 0 auto; }
</style>
