<template>
  <SettingsPageShell title="模型" wide>
    <header class="model-page__header"><div><h1>模型</h1><p>仅支持 OpenAI 兼容协议 API。API Key 仅保存在主进程加密存储中。</p></div><el-button type="primary" @click="openCreate"><AppIcon name="Plus" />添加模型</el-button></header>
    <section v-loading="loading" class="model-grid">
      <article v-for="provider in providers" :key="provider.id" class="model-card">
        <div class="model-card__top"><span class="provider-mark"><AppIcon :name="providerIcon(provider.providerKey)" /></span><div><h2>{{ provider.models.join('、') }}</h2><p>{{ provider.name }}</p></div><el-tag size="small" :type="provider.enabled ? 'success' : 'info'">{{ provider.enabled ? '已启用' : '已停用' }}</el-tag></div>
        <dl><div><dt>Endpoint</dt><dd :title="provider.endpoint">{{ provider.endpoint }}</dd></div><div><dt>密钥</dt><dd><AppIcon :name="provider.hasApiKey ? 'CircleCheck' : 'Warning'" />{{ provider.hasApiKey ? '已配置' : '未配置' }}</dd></div></dl>
        <footer><el-button text @click="test(provider)"><AppIcon name="Connection" />测试</el-button><el-button text @click="edit(provider)"><AppIcon name="EditPen" />编辑</el-button><el-button text type="danger" @click="remove(provider.id)"><AppIcon name="Delete" />删除</el-button></footer>
      </article>
      <button v-if="!loading" type="button" class="model-card model-card--add" @click="openCreate"><AppIcon name="Plus" /><strong>添加模型</strong><span>从供应商开始配置</span></button>
    </section>
    <el-empty v-if="!loading && !providers.length" description="还没有配置模型"><el-button type="primary" @click="openCreate">添加模型</el-button></el-empty>
    <el-dialog v-model="visible" :title="form.id ? '编辑模型' : '添加模型'" width="min(560px, calc(100vw - 32px))" destroy-on-close>
      <p class="dialog-note">仅支持 OpenAI 兼容协议 API</p>
      <el-form label-position="top"><el-form-item label="供应商"><el-select v-model="form.providerKey" @change="applyPreset"><el-option v-for="preset in MODEL_PROVIDER_PRESETS" :key="preset.key" :label="preset.name" :value="preset.key" /></el-select></el-form-item><el-form-item label="API Key"><el-input v-model="form.apiKey" type="password" show-password :placeholder="form.id ? '留空则保持现有密钥' : '输入 API Key'" /></el-form-item><el-form-item label="模型 ID"><el-input v-model="modelsText" placeholder="多个模型用英文逗号分隔" /></el-form-item><el-form-item label="Endpoint"><el-input v-model="form.endpoint" :disabled="endpointLocked" placeholder="https://api.example.com/v1" /></el-form-item><el-form-item label="状态"><el-switch v-model="form.enabled" active-text="启用" inactive-text="停用" /></el-form-item></el-form>
      <template #footer><el-button @click="visible = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template>
    </el-dialog>
  </SettingsPageShell>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref, toRaw } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getPlatformApi } from '@/platform'
import { MODEL_PROVIDER_PRESETS, type ModelProviderInput, type ModelProviderKey, type ModelProviderSummary } from '@/config/harness'
import SettingsPageShell from '../settings/components/SettingsPageShell.vue'
const providers = ref<ModelProviderSummary[]>([]); const loading = ref(false); const saving = ref(false); const visible = ref(false); const modelsText = ref('')
const form = reactive<ModelProviderInput>({ providerKey: 'glm', name: '', endpoint: '', apiKey: '', models: [], enabled: true })
const endpointLocked = computed(() => form.providerKey !== 'ollama' && form.providerKey !== 'custom')
function providerIcon(key: ModelProviderKey) { return ({ glm: 'Connection', kimi: 'ChatDotRound', minimax: 'MagicStick', deepseek: 'Search', ollama: 'Monitor', custom: 'Operation' } as Record<ModelProviderKey, string>)[key] }
async function load() { loading.value = true; try { providers.value = await getPlatformApi()?.listModelProviders() || [] } finally { loading.value = false } }
function applyPreset() { const preset = MODEL_PROVIDER_PRESETS.find(item => item.key === form.providerKey)!; form.name = preset.name; form.endpoint = preset.endpoint; form.models = [...preset.models]; modelsText.value = form.models.join(', ') }
function openCreate() { Object.assign(form, { id: undefined, providerKey: 'glm', apiKey: '', enabled: true }); applyPreset(); visible.value = true }
function edit(row: ModelProviderSummary) { Object.assign(form, { id: row.id, providerKey: row.providerKey, name: row.name, endpoint: row.endpoint, apiKey: '', models: [...row.models], enabled: row.enabled }); modelsText.value = row.models.join(', '); visible.value = true }
async function save() { const api = getPlatformApi(); if (!api) return ElMessage.error('模型仅支持在 Mira 桌面端保存'); saving.value = true; try { const input = { ...toRaw(form), models: modelsText.value.split(',').map(item => item.trim()).filter(Boolean), apiKey: form.apiKey?.trim() || undefined }; await api.saveModelProvider(input); visible.value = false; ElMessage.success('模型已保存'); await load() } catch (error) { ElMessage.error(error instanceof Error ? error.message : '模型保存失败') } finally { saving.value = false } }
async function test(row: ModelProviderSummary) { const api = getPlatformApi(); const modelId = row.models[0]; if (!api || !modelId) return ElMessage.error('请先配置模型 ID'); try { const result = await api.testModelProvider({ id: row.id, providerKey: row.providerKey, name: row.name, endpoint: row.endpoint, apiKey: '', models: [...row.models], enabled: row.enabled }, modelId); ElMessage[result.ok ? 'success' : 'error'](result.text) } catch (error) { ElMessage.error(error instanceof Error ? error.message : '测试失败') } }
async function remove(id: string) { try { await ElMessageBox.confirm('删除模型后不能恢复。', '删除模型', { type: 'warning' }); await getPlatformApi()?.deleteModelProvider(id); await load() } catch {} }
onMounted(load)
</script>
<style scoped lang="scss">
.model-page__header { display:flex; align-items:flex-start; justify-content:space-between; gap:$spacing-lg; margin-bottom:$spacing-xl; }.model-page__header h1 { margin:0; color:var(--cp-text); font-size:$font-2xl; }.model-page__header p { margin:$spacing-sm 0 0; color:var(--cp-text-secondary); font-size:$font-sm; }.model-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:$spacing-md; }.model-card { display:flex; min-width:0; min-height:210px; flex-direction:column; padding:20px; text-align:left; background:var(--cp-bg-elevated); border:1px solid var(--cp-border); border-radius:$radius-md; box-shadow:$shadow-sm; transition:border-color $transition-fast, box-shadow $transition-fast, transform $transition-fast; }.model-card:hover { border-color:color-mix(in srgb,var(--cp-primary) 45%,var(--cp-border)); box-shadow:$shadow; transform:translateY(-1px); }.model-card__top { display:flex; min-width:0; align-items:center; gap:12px; }.model-card__top > div { min-width:0; flex:1; }.provider-mark { display:grid; width:38px; height:38px; place-items:center; color:var(--cp-primary); background:var(--cp-primary-lighter); border-radius:$radius-md; font-size:19px; }.model-card h2 { overflow:hidden; margin:0; color:var(--cp-text); font-size:$font-base; text-overflow:ellipsis; white-space:nowrap; }.model-card__top p { margin:3px 0 0; color:var(--cp-text-secondary); font-size:$font-xs; }.model-card dl { display:grid; gap:10px; margin:20px 0 auto; }.model-card dl div { min-width:0; }.model-card dt { margin-bottom:3px; color:var(--cp-text-tertiary); font-size:11px; }.model-card dd { display:flex; align-items:center; gap:5px; margin:0; overflow:hidden; color:var(--cp-text-secondary); font-size:$font-xs; text-overflow:ellipsis; white-space:nowrap; }.model-card footer { display:flex; gap:4px; margin-top:$spacing-lg; padding-top:$spacing-sm; border-top:1px solid var(--cp-border-light); }.model-card--add { align-items:center; justify-content:center; color:var(--cp-text-secondary); cursor:pointer; background:transparent; border-style:dashed; font:inherit; }.model-card--add .app-icon { margin-bottom:$spacing-sm; color:var(--cp-primary); font-size:22px; }.model-card--add strong { color:var(--cp-text); font-size:$font-sm; }.model-card--add span { margin-top:4px; font-size:$font-xs; }.dialog-note { margin:0 0 $spacing-lg; padding:$spacing-sm $spacing-md; color:var(--cp-text-secondary); background:var(--cp-bg-hover); border-radius:$radius-sm; font-size:$font-xs; } @include media-max($breakpoint-md) { .model-page__header { align-items:stretch; flex-direction:column; }.model-grid { grid-template-columns:1fr; }.model-page__header :deep(.el-button) { align-self:flex-start; } }
</style>
