<template>
  <main class="editor-workspace">
    <header class="workspace-header"><div><h1>{{ project.title }}</h1><p>{{ currentStageLabel }}</p></div><div class="workspace-actions"><el-select :model-value="workspaceSettings.modelSelection ? `${workspaceSettings.modelSelection.providerId}:${workspaceSettings.modelSelection.modelId}` : ''" size="small" style="width:190px" placeholder="选择模型" @update:model-value="$emit('model-change', $event)"><el-option v-for="option in modelOptions" :key="option.value" :label="option.label" :value="option.value" /></el-select><span class="save-state" :class="{ saving }"><i></i>{{ saving ? '正在保存' : '已保存' }}</span><el-button text aria-label="打开工具" @click="$emit('open-tool', 'knowledge')"><AppIcon name="Collection" />知识库</el-button><el-dropdown @command="$emit('export', $event)"><el-button text><AppIcon name="tabler:book-download" />导出</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="json">完整项目 JSON</el-dropdown-item><el-dropdown-item command="markdown">Markdown 创作稿</el-dropdown-item><el-dropdown-item command="text">TXT 创作稿</el-dropdown-item><el-dropdown-item divided command="import"><AppIcon name="tabler:book-upload" />导入完整项目 JSON</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div></header>
    <div v-if="activeStage === 'setup'" class="editor-mode-toolbar"><span>偏好 <el-tooltip content="切换编辑器可能丢失复杂样式，内容会自动转换。" placement="top"><AppIcon style="font-size: 16px;" name="tabler:question-circle" /></el-tooltip></span><el-button-group size="small"><el-button :type="workspaceSettings.editorMode === 'markdown' ? 'primary' : undefined" aria-label="Markdown 编辑器" title="Markdown 编辑器" @click="$emit('editor-mode', 'markdown')">Markdown</el-button><el-button :type="workspaceSettings.editorMode === 'rich' ? 'primary' : undefined" aria-label="富文本编辑器" title="富文本编辑器" @click="$emit('editor-mode', 'rich')">RTE</el-button></el-button-group></div>
    <div class="stage-tabs" role="tablist"><button v-for="item in stages" :key="item.key" type="button" :class="{ active: activeStage === item.key }" @click="$emit('stage-change', item.key)">{{ item.title }}</button></div>
    <div class="editor-scroll-content">
    <section v-if="activeStage === 'setup'" class="stage-content setup-editors"><NovelSetupEditor v-for="field in setupFields" :key="field.key" v-model="project.story[field.key]" :label="field.label" :placeholder="field.placeholder" :editor-mode="workspaceSettings.editorMode" /></section>
    <section v-else-if="activeStage === 'outline'" class="stage-content"><div class="editor-label"><strong>故事总纲</strong><span>{{ countWords(project.outline) }} 字</span></div><textarea v-model="project.outline" class="writing-editor" placeholder="先写下故事的核心冲突、主线和转折，或让创作模型从作品设定中生成。" @contextmenu="$emit('context-menu', $event, 'outline')"></textarea><div class="editor-footer"><span>选中文本后可右键调用 AI 操作</span><div><el-button @click="$emit('run-outline')">生成总纲</el-button><el-button type="primary" @click="$emit('open-tool', 'mindMap')"><AppIcon name="Share" />从总纲构建思维导图</el-button></div></div></section>
    <section v-else-if="activeStage === 'chapter'" class="stage-content"><template v-if="selectedChapter"><div class="chapter-title-row"><div class="chapter-title-control" :class="{ 'is-generating': generatingChapterTitle }"><el-input v-model="selectedChapter.title" aria-label="章节标题" :disabled="generatingChapterTitle" /><el-tooltip content="使用 AI 生成章节名称"><el-button circle text type="primary" aria-label="使用 AI 生成章节名称" :disabled="generatingChapterTitle" @click="$emit('generate-chapter-title')"><AppIcon name="material-symbols:wand-stars-outline" /></el-button></el-tooltip></div><div><el-tooltip content="上移章节"><el-button circle text aria-label="上移章节" :disabled="chapterIndex === 0" @click="$emit('move-chapter', -1)"><AppIcon name="ArrowUp" /></el-button></el-tooltip><el-tooltip content="下移章节"><el-button circle text aria-label="下移章节" :disabled="chapterIndex === project.chapters.length - 1" @click="$emit('move-chapter', 1)"><AppIcon name="ArrowDown" /></el-button></el-tooltip><el-tooltip content="删除章节"><el-button circle text type="danger" aria-label="删除章节" @click="$emit('remove-chapter')"><AppIcon name="Delete" /></el-button></el-tooltip></div></div><div class="editor-label"><strong>章节细纲</strong><span>{{ countWords(selectedChapter.outline) }} 字</span></div><textarea v-model="selectedChapter.outline" class="writing-editor chapter-outline" placeholder="描述本章的核心事件、人物动机、冲突、伏笔与结尾钩子。" @contextmenu="$emit('context-menu', $event, 'chapter')"></textarea><div class="editor-footer"><span>章节细纲会作为正文生成上下文</span><div><el-button @click="$emit('run-chapter-outline')">生成细纲</el-button><el-button type="primary" @click="$emit('stage-change', 'content')">开始写正文</el-button></div></div></template><el-empty v-else description="新建章节后开始编写细纲"><el-button type="primary" @click="$emit('add-chapter')">新建章节</el-button></el-empty></section>
    <section v-else class="stage-content"><template v-if="selectedChapter"><div class="editor-label"><strong>{{ selectedChapter.title }} · 正文</strong><span>{{ countWords(selectedChapter.content) }} 字</span></div><textarea v-model="selectedChapter.content" class="writing-editor content-editor" placeholder="在这里写作，或使用右侧 AI 工作台继续创作。" @contextmenu="$emit('context-menu', $event, 'content')"></textarea><div class="editor-footer"><span>自动保存到本机 SQLite 项目库</span><div><el-button @click="$emit('run-content')">生成正文</el-button><el-button type="primary" @click="$emit('continue-content')"><AppIcon name="EditPen" />继续创作</el-button></div></div></template><el-empty v-else description="请先新建并选择一个章节"><el-button type="primary" @click="$emit('add-chapter')">新建章节</el-button></el-empty></section>
    </div>
  </main>
</template>

<script setup lang="ts">
import NovelSetupEditor from '../components/NovelSetupEditor.vue'
import type { NovelChapter, NovelProjectDocument, NovelWorkspaceSettings } from '@/config/novel'
import type { EditorTarget, SetupField, Stage, StageDefinition, Tool } from '../types'

defineProps<{ project: NovelProjectDocument; activeStage: Stage; stages: StageDefinition[]; setupFields: SetupField[]; selectedChapter?: NovelChapter; chapterIndex: number; saving: boolean; generatingChapterTitle: boolean; workspaceSettings: NovelWorkspaceSettings; modelOptions: Array<{ value: string, label: string }>; currentStageLabel: string }>()
defineEmits<{
  'open-tool': [tool: Tool]
  export: [command: string]
  'editor-mode': [mode: 'markdown' | 'rich']
  'model-change': [value: string]
  'stage-change': [stage: Stage]
  'context-menu': [event: MouseEvent, target: EditorTarget]
  'run-outline': []
  'generate-chapter-title': []
  'move-chapter': [direction: number]
  'remove-chapter': []
  'run-chapter-outline': []
  'run-content': []
  'continue-content': []
  'add-chapter': []
}>()

function countWords(value: string) { return value.trim().length }
</script>

<style scoped lang="scss">
.editor-workspace { display: flex; min-width: 0; flex-direction: column; padding: 24px 28px 20px; overflow: hidden; }.workspace-header, .editor-footer, .editor-label, .chapter-title-row { display: flex; align-items: center; justify-content: space-between; gap: $spacing-sm; }.workspace-header { flex: 0 0 auto; align-items: flex-start; }.workspace-header h1 { margin: 0; color: var(--cp-text); font-size: 20px; font-weight: $font-semibold; }.workspace-header p { margin: 5px 0 0; color: var(--cp-text-secondary); font-size: $font-sm; }.workspace-actions { display: flex; align-items: center; gap: 2px; }.workspace-actions :deep(.el-button) { padding: 4px 6px; color: var(--cp-text-secondary); }.save-state { display: inline-flex; align-items: center; gap: 5px; margin-right: $spacing-xs; color: var(--cp-text-tertiary); font-size: $font-xs; white-space: nowrap; }.save-state i { width: 6px; height: 6px; background: var(--cp-success); border-radius: 50%; }.save-state.saving i { background: var(--cp-warning); }
.editor-scroll-content { min-height: 0; flex: 1; overflow: auto; scrollbar-width: none; }.editor-scroll-content::-webkit-scrollbar { display: none; }
.stage-tabs { display: flex; gap: $spacing-lg; margin: 24px 0 20px; border-bottom: 1px solid var(--cp-border); }.stage-tabs button { position: relative; padding: 0 2px 10px; color: var(--cp-text-secondary); cursor: pointer; background: transparent; border: 0; font: inherit; font-size: $font-sm; }.stage-tabs button.active { color: var(--cp-text); font-weight: $font-medium; }.stage-tabs button.active::after { position: absolute; right: 0; bottom: -1px; left: 0; height: 2px; content: ''; background: var(--cp-primary); }
.stage-content { min-height: 0; }.editor-mode-toolbar { display: flex; align-items: center; justify-content: flex-end; gap: $spacing-sm; margin-top: $spacing-md; color: var(--cp-text-secondary); font-size: $font-xs; }.setup-editors { display: flex; flex-direction: column; gap: $spacing-lg; }.editor-label { margin-bottom: $spacing-sm; }.editor-label strong { color: var(--cp-text); font-size: $font-sm; }.editor-label span, .editor-footer > span { color: var(--cp-text-tertiary); font-size: $font-xs; }.writing-editor { display: block; width: 100%; min-height: 390px; padding: $spacing-md; color: var(--cp-text); resize: vertical; background: var(--cp-bg-elevated); border: 1px solid var(--cp-border); border-radius: $radius-md; outline: 0; font: inherit; font-size: $font-sm; line-height: 1.8; }.writing-editor:focus { border-color: var(--cp-primary); box-shadow: 0 0 0 3px var(--cp-primary-lighter); }.chapter-outline { min-height: 260px; }.content-editor { min-height: 480px; }.editor-footer { margin-top: $spacing-sm; }.editor-footer > div { display: flex; gap: $spacing-sm; }.chapter-title-row { margin-bottom: $spacing-lg; }.chapter-title-control { display: flex; align-items: center; gap: $spacing-xs; min-width: 0; }.chapter-title-control :deep(.el-input) { width: min(360px, 50vw); }.chapter-title-control.is-generating :deep(.el-input__wrapper) { overflow: hidden; background: var(--cp-bg) !important; }.chapter-title-control.is-generating :deep(.el-input__wrapper)::after { position: absolute; top: 0; bottom: 0; width: 42%; content: ''; pointer-events: none; background: linear-gradient(90deg, transparent, var(--cp-primary-lighter), transparent); animation: chapter-title-shimmer 1.35s ease-in-out infinite; }.chapter-title-control.is-generating :deep(.el-input__inner) { color: var(--cp-text-tertiary); }.chapter-title-row > div:last-child { display: flex; } @keyframes chapter-title-shimmer { from { transform: translateX(-160%); } to { transform: translateX(340%); } } @media (prefers-reduced-motion: reduce) { .chapter-title-control.is-generating :deep(.el-input__wrapper)::after { animation: none; opacity: .55; transform: translateX(70%); } }
@include media-max($breakpoint-md) { .editor-workspace { padding: $spacing-md; }.workspace-header, .editor-footer { align-items: flex-start; flex-direction: column; }.workspace-actions { flex-wrap: wrap; } }
</style>
